services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - ./n8n:/home/node/.n8n
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge